In [1]:
#Importing Necessary Libraries

import numpy as np
import qutip as qt
from qutip import tensor
from qiskit.visualization import array_to_latex
from scipy.linalg import expm

In [2]:
theta=np.complex(0,np.pi/4) #50-50 Beam splitter

#truncated bosonic operators

bdag_theory=adag_theory=qt.create(3)
a_theory=b_theory=qt.destroy(3)  

#spin raising and lowering operator
sig_p=qt.destroy(2)
sig_m=qt.create(2)

#Pauli operators
I=qt.identity(2)
sig_z=qt.sigmaz()
sig_x=qt.sigmax()
sig_y=qt.sigmay()

#Qubit states
ket_0=qt.fock(2,0)
ket_1=qt.fock(2,1)

In [3]:
#formulating b and b dagger in terms of spin operators
bdag=adag=tensor(sig_p,sig_m,I)+np.sqrt(2)*tensor(I,sig_p,sig_m)
b=a=tensor(sig_m,sig_p,I)+np.sqrt(2)*tensor(I,sig_m,sig_p)

### Problem of $\hat{b}$ and $\hat{b}^{\dagger}$

In [4]:
bdag

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.41421356 0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         1.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  1.41421356 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]

### |100> $\rightarrow$ |010>

In [5]:
bdag*tensor(ket_1,ket_0,ket_0) #|0>
#tensor(ket_0,ket_1,ket_0) #|1>

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

### |010> $\rightarrow$ |001>

In [6]:
bdag*tensor(ket_0,ket_1,ket_0) #|1>

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

Not only the above mentioned states, it also acts on other states also. And result in following transformations.

### |110> $\rightarrow$ |101>

In [7]:
bdag*tensor(ket_1,ket_1,ket_0)

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [1.41421356]
 [0.        ]
 [0.        ]]

### |101> $\rightarrow$ |011>

In [8]:
bdag*tensor(ket_1,ket_0,ket_1)

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]]

#### It happens due to the presence of redundant element in the operator $\hat{b}$ and $\hat{b}^{\dagger}$. We need to have $\hat{b}$ and $\hat{b}^{\dagger}$ in the following form.

In [9]:
bdag=np.array(bdag)
bdag[3,5]=0
bdag[5,6]=0

b=np.array(b)
b[5,3]=0
b[6,5]=0

adag=bdag 
a=b


print(r'bdagger')

array_to_latex(bdag)

bdagger


<IPython.core.display.Latex object>

In [10]:
print('b=')

array_to_latex(b)

b=


<IPython.core.display.Latex object>

## Modification of mapping needed

Creation operator

$b^{\dagger} = \frac{1}{2}(\sigma_{+}^{0} \otimes \sigma_{-}^{1} \otimes I)+ \frac{\sqrt2}{2}(I\otimes \sigma_{+}^{1}\otimes \sigma_{-}^{2})+\frac{1}{2}(\sigma_{+}^{0} \otimes \sigma_{-}^{1} \otimes \sigma_{z}^{2})+ \frac{\sqrt2}{2}(\sigma_{z}^{1} \otimes \sigma_{+}^{1}\otimes \sigma_{-}^{2})$

or

$b^{\dagger} = \frac{1}{2}(\sigma_{+}^{0} \otimes \sigma_{-}^{1} \otimes I^{(2)}+\sigma_{+}^{0} \otimes \sigma_{-}^{1} \otimes \sigma_{z}^{2})+ \frac{1}{\sqrt2}(I^{(0)}\otimes \sigma_{+}^{1}\otimes \sigma_{-}^{2}+\sigma_{z}^{0} \otimes \sigma_{+}^{1}\otimes \sigma_{-}^{2})$

Annihilation Operator

$b = \frac{1}{2}(\sigma_{-}^{0} \otimes \sigma_{+}^{1} \otimes I^{(2)}+\sigma_{-}^{0} \otimes \sigma_{+}^{1} \otimes \sigma_{z}^{2})+ \frac{1}{\sqrt2}(I^{(0)}\otimes \sigma_{-}^{1}\otimes \sigma_{+}^{2}+\sigma_{z}^{0} \otimes \sigma_{-}^{1}\otimes \sigma_{+}^{2})$

### Verifying HOM effect using New Mapping Scheme

In [11]:
b=a=(1/2)*(tensor(sig_m,sig_p,I)+tensor(sig_m,sig_p,sig_z))+(1/np.sqrt(2))*(tensor(I,sig_m,sig_p)+tensor(sig_z,sig_m,sig_p))

In [12]:
bdag=adag=(1/2)*(tensor(sig_p,sig_m,I)+tensor(sig_p,sig_m,sig_z))+(1/np.sqrt(2))*(tensor(I,sig_p,sig_m)+tensor(sig_z,sig_p,sig_m))

In [13]:
B=theta*(tensor(bdag,a)+tensor(b,adag))
U=B.expm()
U

Quantum object: dims = [[2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2]], shape = (64, 64), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]]

In [14]:
input_state=tensor(ket_0,ket_1,ket_0,ket_0,ket_1,ket_0) #|1>|1>
#input_state
output_state=U*input_state

np.abs(np.array(output_state))

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

## Verifying HOM effect by expanding terms in the exponent of Unitary

In [15]:
Op0134_a=tensor(sig_p,sig_m,I,sig_m,sig_p,I)+tensor(sig_m,sig_p,I,sig_p,sig_m,I)
Op0134_b=tensor(sig_p,sig_m,sig_z,sig_m,sig_p,I)+tensor(sig_m,sig_p,sig_z,sig_p,sig_m,I)
Op0134_c=tensor(sig_p,sig_m,I,sig_m,sig_p,sig_z)+tensor(sig_m,sig_p,I,sig_p,sig_m,sig_z)
Op0134_d=tensor(sig_p,sig_m,sig_z,sig_m,sig_p,sig_z)+tensor(sig_m,sig_p,sig_z,sig_p,sig_m,sig_z,)
Op0134=Op0134_a+Op0134_b+Op0134_c+Op0134_d

In [16]:
Op0145_a=tensor(sig_p,sig_m,I,I,sig_m,sig_p)+tensor(sig_m,sig_p,I,I,sig_p,sig_m)
Op0145_b=tensor(sig_p,sig_m,sig_z,I,sig_m,sig_p)+tensor(sig_m,sig_p,sig_z,I,sig_p,sig_m)
Op0145_c=tensor(sig_p,sig_m,I,sig_z,sig_m,sig_p)+tensor(sig_m,sig_p,I,sig_z,sig_p,sig_m)
Op0145_d=tensor(sig_p,sig_m,sig_z,sig_z,sig_m,sig_p)+tensor(sig_m,sig_p,sig_z,sig_z,sig_p,sig_m)
Op0145=Op0145_a+Op0145_b+Op0145_c+Op0145_d

In [17]:
Op1234_a=tensor(I,sig_p,sig_m,sig_m,sig_p,I)+tensor(I,sig_m,sig_p,sig_p,sig_m,I)
Op1234_b=tensor(sig_z,sig_p,sig_m,sig_m,sig_p,I)+tensor(sig_z,sig_m,sig_p,sig_p,sig_m,I)
Op1234_c=tensor(I,sig_p,sig_m,sig_m,sig_p,sig_z)+tensor(I,sig_m,sig_p,sig_p,sig_m,sig_z)
Op1234_d=tensor(sig_z,sig_p,sig_m,sig_m,sig_p,sig_z)+tensor(sig_z,sig_m,sig_p,sig_p,sig_m,sig_z,)
Op1234=Op1234_a+Op1234_b+Op1234_c+Op1234_d


In [18]:
Op1245_a=tensor(I,sig_p,sig_m,I,sig_m,sig_p)+tensor(I,sig_m,sig_p,I,sig_p,sig_m)
Op1245_b=tensor(sig_z,sig_p,sig_m,I,sig_m,sig_p)+tensor(sig_z,sig_m,sig_p,I,sig_p,sig_m)
Op1245_c=tensor(I,sig_p,sig_m,sig_z,sig_m,sig_p)+tensor(I,sig_m,sig_p,sig_z,sig_p,sig_m)
Op1245_d=tensor(sig_z,sig_p,sig_m,sig_z,sig_m,sig_p)+tensor(sig_z,sig_m,sig_p,sig_z,sig_p,sig_m)
Op1245=Op1245_a+Op1245_b+Op1245_c+Op1245_d

In [19]:
c1=1/2
c2=1/(2*np.sqrt(2))

U=(theta*((c1**2)*(Op0134)+c2*(Op0145+Op1234)+c1*(Op1245))).expm()

In [20]:
input_state=tensor(ket_0,ket_1,ket_0,ket_0,ket_1,ket_0)

output_state=U*input_state
np.abs(np.array(output_state)) #shows HOM effect

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

## Checking the Commutation Relations

#### Checking commutation of 0134 term

In [21]:
commutator_1=Op0134*Op0145-Op0145*Op0134
np.any(np.array(commutator_1))

False

In [22]:
commutator_2=Op0134*Op1234-Op1234*Op0134
np.any(np.array(commutator_2))

False

In [23]:
commutator_3=Op0134*Op1245-Op1245*Op0134
np.any(np.array(commutator_3))

False

#### Checking commutation of 0145 term

In [24]:
commutator_4=Op0145*Op1234-Op1234*Op0145
np.any(np.array(commutator_4))

True

In [25]:
commutator_5=Op0145*Op1245-Op1245*Op0145
np.any(np.array(commutator_5))

False

#### Checking commutation of 1234 term

In [26]:
commutator_6=Op1234*Op1245-Op1245*Op1234
np.any(np.array(commutator_6))

False

In [27]:
### Combining non-commuting operators

U0134=(theta*((c1**2)*(Op0134))).expm()
U1245=(theta*c1*(Op1245)).expm()

#U0145+U1234
U0145_1234=(theta*c2*(Op0145+Op1234)).expm()

In [28]:
U=U0134*U1245*U0145_1234

In [29]:
input_state=tensor(ket_0,ket_1,ket_0,ket_0,ket_1,ket_0)

output_state=U*input_state
np.abs(np.array(output_state)) #shows HOM effect

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

### Checking the commuatation of terms in 0145

In [30]:
com_1=Op0145_a*Op0145_b-Op0145_b*Op0145_a
np.any(np.array(com_1))

False

In [31]:
com_2=Op0145_a*Op0145_c-Op0145_c*Op0145_a
np.any(np.array(com_2))

False

In [34]:
com_3=Op0145_a*Op0145_d-Op0145_d*Op0145_a
np.any(np.array(com_3))

False

In [35]:
com_4=Op0145_b*Op0145_c-Op0145_c*Op0145_b
np.any(np.array(com_4))

False

In [37]:
com_5=Op0145_b*Op0145_d-Op0145_d*Op0145_b
np.any(np.array(com_5))

False

In [38]:
com_6=Op0145_c*Op0145_d-Op0145_d*Op0145_c
np.any(np.array(com_6))

False

### Checking the commuatation of terms in 1234

In [40]:
com_1=Op1234_a*Op1234_b-Op1234_b*Op1234_a
np.any(np.array(com_1))

False

In [42]:
com_2=Op1234_a*Op1234_c-Op1234_c*Op1234_a
np.any(np.array(com_2))

False

In [43]:
com_3=Op1234_a*Op1234_d-Op1234_d*Op1234_a
np.any(np.array(com_3))

False

In [44]:
com_4=Op1234_b*Op1234_c-Op1234_c*Op1234_b
np.any(np.array(com_4))

False

In [45]:
com_5=Op1234_b*Op1234_d-Op1234_d*Op1234_b
np.any(np.array(com_5))

False

In [46]:
com_6=Op1234_c*Op1234_d-Op1234_d*Op1234_c
np.any(np.array(com_6))

False