In [1]:
#Importing Necessary Libraries

import numpy as np
import qutip as qt
from qutip import tensor
from scipy.linalg import expm

## Unitary of the Beam Splitter

### $U=\exp(i\theta(\hat{b}^{\dagger}\hat{a}+\hat{b}\hat{a}^{\dagger}))$

$\theta \rightarrow \text{Parameter of Beam splitter}\newline$
$\hat{b}^{\dagger},\hat{b} \rightarrow \text{Bosonic Creation and Annihilation Operator}\newline$
$a$ & $b$  represents 2 modes

In [2]:
theta=np.complex(0,np.pi/4) #50-50 Beam splitter

#truncated bosonic operators

bdag_theory=adag_theory=qt.create(3)
a_theory=b_theory=qt.destroy(3)  

#spin raising and lowering operator
sig_p=qt.destroy(2)
sig_m=qt.create(2)

#Pauli operators
I=qt.identity(2)
sig_z=qt.sigmaz()
sig_x=qt.sigmax()
sig_y=qt.sigmay()

#Qubit states
ket_0=qt.fock(2,0)
ket_1=qt.fock(2,1)

## HOM Effect Theory

##### $B=\hat{b}^{\dagger}\hat{a}+\hat{b}\hat{a}^{\dagger}$

In [3]:
B_theory=tensor(bdag_theory,a_theory)+tensor(b_theory,adag_theory) 
B_theory

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = True
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         1.41421356 0.
  0.         0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.         0.
  1.41421356 0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         2.         0.        ]
 [0.         0.         0.         0.         1.41421356 0.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         2.
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]]

In [4]:
Bdag_theory=B_theory.dag()
#Checking whether B is Unitary
B_theory*Bdag_theory == qt.identity(np.shape(B_theory)[0])

False

Unitary of Beam splitter, $U=\exp(i\theta B)$

If B is unitary, then $\exp(i\theta B) = \cos(\theta)\mathcal{I}-i\sin(\theta)B$.

Since B is not Unitary, we need to perform series expansion.

In [5]:
B_theory=theta*B_theory
U_theory=B_theory.expm()
U_theory

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = False
Qobj data =
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.70710678+0.j          0.        +0.j
   0.        +0.70710678j  0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.5       +0.j
   0.        +0.j          0.        +0.70710678j  0.        +0.j
  -0.5       +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.70710678j  0.        +0.j
   0.70710678+0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.70710678j
 

In theory, vector form of fock states are given $$|0> =\begin{bmatrix}1\\0\\0\end{bmatrix}$$\
$$|1> =\begin{bmatrix}0\\1\\0\end{bmatrix}$$\
$$|2> =\begin{bmatrix}0\\0\\1\end{bmatrix}$$

In [6]:
ket1=qt.fock(3,1)
inp_theory=tensor(ket1,ket1) # input state |1>|1>
out_theory=U_theory*inp_theory
out_theory

Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[0.+0.j        ]
 [0.+0.j        ]
 [0.+0.70710678j]
 [0.+0.j        ]
 [0.+0.j        ]
 [0.+0.j        ]
 [0.+0.70710678j]
 [0.+0.j        ]
 [0.+0.j        ]]

## HOM Effect with Spin operator

### Mapping of bosonic operators

$\hat{b}^{\dagger}=\sigma_{+}^{0}\sigma_{-}^{1}+\sqrt{2}\sigma_{+}^{1}\sigma_{-}^{2}$\
\
$\hat{b}=\sigma_{-}^{0}\sigma_{+}^{1}+\sqrt{2}\sigma_{-}^{1}\sigma_{+}^{2}$

In [7]:
#formulating b and b dagger in terms of spin operators
bdag=adag=tensor(sig_p,sig_m,I)+np.sqrt(2)*tensor(I,sig_p,sig_m)
b=a=tensor(sig_m,sig_p,I)+np.sqrt(2)*tensor(I,sig_m,sig_p)

#calculating B operator
B=theta*(tensor(bdag,a)+tensor(b,adag))

#Unitary of Beam Splitter
U=B.expm()
U 

Quantum object: dims = [[2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2]], shape = (64, 64), type = oper, isherm = False
Qobj data =
[[1.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 1.+0.j]]

We use unary encoding to encode the fock states to qubit 

$|0> = |100>$\
$|1> = |010>$\
$|2> = |001>$


In [8]:
input_state=tensor(ket_0,ket_1,ket_0,ket_0,ket_1,ket_0) #|1>|1>
#input_state
output_state=U*input_state

np.abs(np.array(output_state))

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

In [9]:
#expected outcome
expect_out=(1/np.sqrt(2))*(tensor(ket_0,ket_0,ket_1,ket_1,ket_0,ket_0)+tensor(ket_1,ket_0,ket_0,ket_0,ket_0,ket_1))
np.abs(np.array(expect_out))

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

HOM effect can be observed numerically.

### Numerical simulation of 
$\exp(i\theta([\sigma_{+}^{0}\sigma_{-}^{1}\sigma_{-}^{3}\sigma_{+}^{4}+\sigma_{-}^{0}\sigma_{+}^{1}\sigma_{+}^{3}\sigma_{-}^{4}] + \sqrt{2}[\sigma_{+}^{0}\sigma_{-}^{1}\sigma_{-}^{4}\sigma_{+}^{5}+\sigma_{-}^{0}\sigma_{+}^{1}\sigma_{+}^{4}\sigma_{-}^{5}]+\sqrt{2}[\sigma_{+}^{1}\sigma_{-}^{2}\sigma_{-}^{3}\sigma_{+}^{4}+\sigma_{-}^{1}\sigma_{+}^{2}\sigma_{+}^{3}\sigma_{-}^{4}]+2[\sigma_{+}^{1}\sigma_{-}^{2}\sigma_{-}^{4}\sigma_{+}^{5}+\sigma_{-}^{1}\sigma_{+}^{2}\sigma_{+}^{4}\sigma_{-}^{5}]
             ))$

In [10]:
# operators corresponding to the 4 operators in the exponent

Op0145=tensor(sig_p,sig_m,I,I,sig_m,sig_p)+tensor(sig_m,sig_p,I,I,sig_p,sig_m)
Op0134=tensor(sig_p,sig_m,I,sig_m,sig_p,I)+tensor(sig_m,sig_p,I,sig_p,sig_m,I)
Op1234=tensor(I,sig_p,sig_m,sig_m,sig_p,I)+tensor(I,sig_m,sig_p,sig_p,sig_m,I)
Op1245=tensor(I,sig_p,sig_m,I,sig_m,sig_p)+tensor(I,sig_m,sig_p,I,sig_p,sig_m)

In [11]:
#checking HOM effect numerically

U=(theta*(Op0134+np.sqrt(2)*Op0145+np.sqrt(2)*Op1234+2*Op1245)).expm()
input_state=tensor(ket_0,ket_1,ket_0,ket_0,ket_1,ket_0)

output_state=U*input_state
np.abs(np.array(output_state)) #shows HOM effect

array([[0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.70710678],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

## Commutation of the terms in the exponent

### Commutation relations of 0134 term

In [12]:
commutator_1=Op0134*Op0145-Op0145*Op0134
np.any(np.array(commutator_1)) #satisfies commutation i.e, 'com' will be a zero matrix.

False

In [13]:
commutator_2=Op0134*Op1234-Op1234*Op0134
np.any(np.array(commutator_2))

False

In [14]:
commutator_3=Op0134*Op1245-Op1245*Op0134
np.any(np.array(commutator_3))

True

i.e, $\textbf{commutator_3}$ will not be a zero matrix, hence terms 0134 and 1245 doesnot commute

### Commutation relations of 0145 term

In [15]:
commutator_4=Op0145*Op1234-Op1234*Op0145
np.any(np.array(commutator_4))

True

i.e, $\textbf{commutator_4}$ will not be a zero matrix, hence terms 1234 and 1245 doesnot commute

In [16]:
commutator_5=Op0145*Op1245-Op1245*Op0145
np.any(np.array(commutator_5))

False

### Commutation relations of 1234 term

In [17]:
commutator_6=Op1234*Op1245-Op1245*Op1234
np.any(np.array(commutator_6))

False

###  ``Thus while constructing quantum circuit we have to perform trotterization``

In [18]:
### Combining non-commuting operators

#U0134+U1245
oper_com_1=tensor(sig_p,sig_m,I,sig_m,sig_p,I)+tensor(sig_m,sig_p,I,sig_p,sig_m,I)+2*(tensor(I,sig_p,sig_m,I,sig_m,sig_p)+tensor(I,sig_m,sig_p,I,sig_p,sig_m))

#U0145+U1234
oper_com_2=np.sqrt(2)*(tensor(sig_p,sig_m,I,I,sig_m,sig_p)+tensor(sig_m,sig_p,I,I,sig_p,sig_m)+tensor(I,sig_p,sig_m,sig_m,sig_p,I)+tensor(I,sig_m,sig_p,sig_p,sig_m,I))

#Checking commutation relations
commutator=oper_com_1*oper_com_2-oper_com_2*oper_com_1
np.any(np.array(commutator))

False

In [19]:
#corresponding unitaries

U_com_1=(theta*oper_com_1).expm()
U_com_2=(theta*oper_com_2).expm()

U_com=U_com_1*U_com_2

In [20]:
input_state=tensor(ket_0,ket_1,ket_0,ket_0,ket_1,ket_0)

output_state=U_com*input_state
np.array(output_state) #Shows HOM effect

array([[0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.70710678j],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.70710678j],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],


### Note 1: Even without trotterization circuit works for single photon experiments

In [21]:
# Unitary corresponding each term of the exponential
# Here we donot assume the non commutavity

U0134=(theta*Op0134).expm()
U0145=(np.sqrt(2)*theta*Op0145).expm()
U1234=(np.sqrt(2)*theta*Op1234).expm()
U1245=(2*theta*Op1245).expm()

In [22]:
U=U0134*U0145*U1234*U1245 # unitary of beam splitter if we neglect non commutavity

#|1>|0>
input_state=tensor(ket_0,ket_1,ket_0,ket_1,ket_0,ket_0)

output_state=U*input_state
np.array(output_state)

array([[0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.70710678+0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.

### Result corresponds to $\frac{1}{\sqrt{2}}(|1>|0>+|0>|1>)$

Similar results can be got for |0>|1> also.