In [1]:
import qutip as qt
import numpy as np
from qutip import tensor
from scipy.linalg import expm

In [2]:
theta=complex(0,np.pi/4) #50-50 Beam splitter

#truncated bosonic operators

bdag_theory=adag_theory=qt.create(3)
a_theory=b_theory=qt.destroy(3)  

#spin raising and lowering operator
sig_p=qt.destroy(2)
sig_m=qt.create(2)

#Pauli operators
I=qt.identity(2)
sig_z=qt.sigmaz()
sig_x=qt.sigmax()
sig_y=qt.sigmay()

#Qubit states
ket_0=qt.fock(2,0)
ket_1=qt.fock(2,1)

#projection operator
P0=(I+sig_z)/2
P1=(I-sig_z)/2

In [3]:
op1=tensor(P0,sig_m,P0,sig_p)+tensor(P0,sig_p,P0,sig_m)
op2=np.sqrt(2)*(tensor(P0,sig_m,sig_p,P1)+tensor(P0,sig_p,sig_m,P1))
op3=np.sqrt(3)*(tensor(P0,sig_m,P1,sig_m)+tensor(P0,sig_p,P1,sig_p))
op4=np.sqrt(2)*(tensor(sig_m,P1,P0,sig_p)+tensor(sig_p,P1,P0,sig_m))
op5=2*(tensor(sig_m,P1,sig_p,P1)+tensor(sig_p,P1,sig_m,P1))
op6=np.sqrt(6)*(tensor(sig_m,P1,P1,sig_m)+tensor(sig_p,P1,P1,sig_p))
op7=np.sqrt(3)*(tensor(P1,sig_p,P0,sig_p)+tensor(P1,sig_m,P0,sig_m))
op8=np.sqrt(6)*(tensor(P1,sig_p,sig_p,P1)+tensor(P1,sig_m,sig_m,P1))
op9=3*(tensor(P1,sig_p,P1,sig_m)+tensor(P1,sig_m,P1,sig_p))

In [7]:
op=tensor(bdag_theory,a_theory)+tensor(b_theory,adag_theory)
U=(theta*op).expm()
U

Quantum object: dims = [[3, 3], [3, 3]], shape = (9, 9), type = oper, isherm = False
Qobj data =
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.70710678+0.j          0.        +0.j
   0.        +0.70710678j  0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.5       +0.j
   0.        +0.j          0.        +0.70710678j  0.        +0.j
  -0.5       +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.70710678j  0.        +0.j
   0.70710678+0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.        +0.70710678j
 

In [4]:
op=op1+op2+op3+op4+op5+op6+op7+op8+op9
U=(theta*op).expm()

inp_state=tensor(ket_1,ket_0,ket_0,ket_0)
np.array(U*inp_state)

array([[ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        -0.35355339j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [-0.61237244+0.j        ],
       [ 0.35355339+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.61237244j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ]])

In [6]:
U

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.70710678+0.j          0.        +0.j
   0.        +0.j          0.        +0.70710678j  0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.35355339+0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.612

In [5]:
inp_state

Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [6]:
np.array(tensor(ket_1,ket_0,ket_0,ket_0)) #30 ==> 0.35 

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [7]:
np.array(tensor(ket_0,ket_0,ket_1,ket_0)) #03 ==> 0.35

array([[0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [8]:
np.array(tensor(ket_1,ket_1,ket_0,ket_1)) #21 ==>0.612

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [9]:
np.array(tensor(ket_0,ket_1,ket_1,ket_1)) #12 ==>0.612

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [10]:
#coherent state

alpha=0.9
c=np.exp(-1*(alpha**2)/2)
c_state=c*(tensor(ket_0,ket_0,ket_0,ket_0)+alpha*tensor(ket_0,ket_1,ket_0,ket_0)+(alpha**2/np.sqrt(2))*tensor(ket_1,ket_1,ket_0,ket_0)+(alpha**3/np.sqrt(6))*tensor(ket_1,ket_0,ket_0,ket_0))

In [11]:
np.array(c_state)

array([[0.66697681+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.60027913+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.19850097+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.3820153 +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j]])

In [12]:
np.array(U*c_state)

array([[ 0.66697681+0.j        ],
       [ 0.        +0.42446144j],
       [ 0.        -0.07018069j],
       [-0.19100765+0.j        ],
       [ 0.42446144+0.j        ],
       [ 0.        +0.27012561j],
       [ 0.        +0.j        ],
       [-0.12155652+0.j        ],
       [ 0.07018069+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.19100765+0.j        ],
       [ 0.        +0.12155652j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ]])

In [13]:
np.array(tensor(ket_1,ket_1,ket_0,ket_1))

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j]])

## Checking the decomposition in terms of gate

In [14]:
oper1=(1/8)*(tensor(I,sig_x,I,sig_x)+tensor(I,sig_y,I,sig_y)+tensor(sig_z,sig_x,sig_z,sig_x)+tensor(sig_z,sig_y,sig_z,sig_y)
       +tensor(I,sig_x,sig_z,sig_x)+tensor(I,sig_y,sig_z,sig_y)+tensor(sig_z,sig_x,I,sig_x)+tensor(sig_z,sig_y,I,sig_y))
oper1==op1

True

In [15]:
c1=np.sqrt(2)/8
oper2=c1*(tensor(I,sig_x,sig_x,I)+tensor(sig_z,sig_y,sig_y,I)-tensor(I,sig_x,sig_x,sig_z)-tensor(sig_z,sig_y,sig_y,sig_z)+tensor(I,sig_y,sig_y,I)+tensor(sig_z,sig_x,sig_x,I)-tensor(I,sig_y,sig_y,sig_z)-tensor(sig_z,sig_x,sig_x,sig_z))
oper2==op2

True

In [16]:
c2=np.sqrt(3)/8
oper3=c2*(tensor(I,sig_x,I,sig_x)-tensor(I,sig_y,I,sig_y)-tensor(sig_z,sig_x,sig_z,sig_x)+tensor(sig_z,sig_y,sig_z,sig_y)-tensor(I,sig_x,sig_z,sig_x)+tensor(I,sig_y,sig_z,sig_y)+tensor(sig_z,sig_x,I,sig_x)-tensor(sig_z,sig_y,I,sig_y))
oper3==op3
    

True

In [17]:
c3=np.sqrt(2)/8
oper4=c3*(tensor(sig_x,I,I,sig_x)+tensor(sig_y,I,I,sig_y)+tensor(sig_x,I,sig_z,sig_x)+tensor(sig_y,I,sig_z,sig_y)-tensor(sig_x,sig_z,I,sig_x)-tensor(sig_y,sig_z,I,sig_y)-tensor(sig_x,sig_z,sig_z,sig_x)-tensor(sig_y,sig_z,sig_z,sig_y))

oper4==op4

True

In [18]:
c4=1/4
oper5=c4*(tensor(sig_x,I,sig_x,I)+tensor(sig_y,I,sig_y,I)-tensor(sig_x,I,sig_x,sig_z)-tensor(sig_y,I,sig_y,sig_z)-tensor(sig_x,sig_z,sig_x,I)-tensor(sig_y,sig_z,sig_y,I)+tensor(sig_x,sig_z,sig_x,sig_z)+tensor(sig_y,sig_z,sig_y,sig_z))

oper5==op5

True

In [19]:
c5=np.sqrt(6)/8

oper6=c5*(tensor(sig_x,I,I,sig_x)-tensor(sig_y,I,I,sig_y)-tensor(sig_x,sig_z,I,sig_x)+tensor(sig_y,sig_z,I,sig_y)-tensor(sig_x,I,sig_z,sig_x)+tensor(sig_y,I,sig_z,sig_y)+tensor(sig_x,sig_z,sig_z,sig_x)-tensor(sig_y,sig_z,sig_z,sig_y))

oper6==op6

True

In [20]:
c6=np.sqrt(3)/8

oper7=c6*(tensor(I,sig_x,I,sig_x)-tensor(I,sig_y,I,sig_y)+tensor(I,sig_x,sig_z,sig_x)-tensor(I,sig_y,sig_z,sig_y)-tensor(sig_z,sig_x,I,sig_x)+tensor(sig_z,sig_y,I,sig_y)-tensor(sig_z,sig_x,sig_z,sig_x)+tensor(sig_z,sig_y,sig_z,sig_y))

oper7==op7

True

In [21]:
c7=np.sqrt(6)/8

oper8=c7*(tensor(I,sig_x,sig_x,I)-tensor(I,sig_y,sig_y,I)-tensor(I,sig_x,sig_x,sig_z)+tensor(I,sig_y,sig_y,sig_z)-tensor(sig_z,sig_x,sig_x,I)+tensor(sig_z,sig_y,sig_y,I)+tensor(sig_z,sig_x,sig_x,sig_z)-tensor(sig_z,sig_y,sig_y,sig_z))

oper8==op8

True

In [22]:
c8=3/8

oper9=c8*(tensor(I,sig_x,I,sig_x)+tensor(I,sig_y,I,sig_y)-tensor(I,sig_x,sig_z,sig_x)-tensor(I,sig_y,sig_z,sig_y)-tensor(sig_z,sig_x,I,sig_x)-tensor(sig_z,sig_y,I,sig_y)+tensor(sig_z,sig_x,sig_z,sig_x)+tensor(sig_z,sig_y,sig_z,sig_y))

oper9==op9

True

In [23]:
c0=(2+np.sqrt(3))/4
c1=(2-np.sqrt(3))/4
c2=-1/4
oper1937=(c0*(tensor(I,sig_x,I,sig_x)+tensor(sig_z,sig_y,sig_z,sig_y))+c1*(tensor(I,sig_y,I,sig_y)+tensor(sig_z,sig_x,sig_z,sig_x))
          +c2*(tensor(I,sig_x,sig_z,sig_x)+tensor(I,sig_y,sig_z,sig_y)+tensor(sig_z,sig_x,I,sig_x)+tensor(sig_z,sig_y,I,sig_y)))


oper1937==(oper1+oper9+oper3+oper7)

True

In [24]:
c1= (np.sqrt(2)+np.sqrt(6))/8
c2= (np.sqrt(2)-np.sqrt(6))/8

oper28=(c1*(tensor(I,sig_x,sig_x,I)+tensor(sig_z,sig_y,sig_y,I)-tensor(I,sig_x,sig_x,sig_z)-tensor(sig_z,sig_y,sig_y,sig_z))
            +c2*(tensor(I,sig_y,sig_y,I)+tensor(sig_z,sig_x,sig_x,I)-tensor(I,sig_y,sig_y,sig_z)-tensor(sig_z,sig_x,sig_x,sig_z)))

oper28==(oper2+oper8)

True

In [25]:
oper46=(c1*(tensor(sig_x,I,I,sig_x)+tensor(sig_y,I,sig_z,sig_y)-tensor(sig_x,sig_z,I,sig_x)-tensor(sig_y,sig_z,sig_z,sig_y))
            +c2*(tensor(sig_y,I,I,sig_y)+tensor(sig_x,I,sig_z,sig_x)-tensor(sig_y,sig_z,I,sig_y)-tensor(sig_x,sig_z,sig_z,sig_x)))

oper46==(oper4+oper6)

True

In [26]:
#op=oper1937+oper28+oper46+oper5
op=oper1937
U=(theta*op).expm()

inp_state=tensor(ket_0,ket_1,ket_0,ket_0)
np.array(U*inp_state)

array([[0.        +0.j        ],
       [0.        +0.70710678j],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.70710678+0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ]])

In [27]:
(1/np.sqrt(2))*(tensor(ket_0,ket_1,ket_0,ket_0)+tensor(ket_0,ket_0,ket_0,ket_1))

Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

## Numerical Simulation of Quantum Circuit

In [28]:
from qutip.qip.circuit import QubitCircuit, Gate

In [29]:
def staircase_circ2(a,b,e,qc):
    
    arr=np.array([a,b])
    
    qc.add_gate('CNOT',targets=arr[0],controls=arr[1])
    
    qc.add_gate('RZ',targets=arr[-1],arg_value=e)
    
    qc.add_gate('CNOT',targets=arr[0],controls=arr[1])
    
    return(qc)

def stepwise_circ3(a,b,c,e,qc):
    
    arr=np.sort([a,b,c])
    
    qc.add_gate('CNOT',targets=arr[0],controls=arr[1])
    qc.add_gate('CNOT',targets=arr[1],controls=arr[2])
    
    qc.add_gate('RZ',targets=arr[-1],arg_value=e)
    
    qc.add_gate('CNOT',targets=arr[0],controls=arr[1])
    qc.add_gate('CNOT',targets=arr[1],controls=arr[2])

    return(qc)
    

## $U_{1937}$

In [30]:
p1=np.pi*(2+np.sqrt(3))/8
p2=np.pi*(2-np.sqrt(3))/8
p3=np.pi/8
p4=np.pi*(2+np.sqrt(6))/16
p5=np.pi*(2-np.sqrt(6))/16


In [31]:
qc1=QubitCircuit(4)

qc1.add_gate('SNOT',targets=1)
qc1.add_gate('SNOT',targets=3)

qc1.add_gate('CNOT',targets=3,controls=1)
    
qc1.add_gate('RZ',targets=3,arg_value=-1*p1)

qc1.add_gate('CNOT',targets=3,controls=1)
qc1.add_gate('SNOT',targets=1)
qc1.add_gate('SNOT',targets=3)

#qc1.png

In [32]:
U1=qc1.propagators()
dim=np.shape(U1[0])[0]
Usim1=U1[0]
i=1
while i<(len(U1)):
    Usim1=Usim1*U1[i]
    i=i+1

Usim1

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[0.7433133+0.j         0.       +0.j         0.       +0.j
  0.       +0.j         0.       +0.j         0.       +0.66894344j
  0.       +0.j         0.       +0.j         0.       +0.j
  0.       +0.j         0.       +0.j         0.       +0.j
  0.       +0.j         0.       +0.j         0.       +0.j
  0.       +0.j        ]
 [0.       +0.j         0.7433133+0.j         0.       +0.j
  0.       +0.j         0.       +0.66894344j 0.       +0.j
  0.       +0.j         0.       +0.j         0.       +0.j
  0.       +0.j         0.       +0.j         0.       +0.j
  0.       +0.j         0.       +0.j         0.       +0.j
  0.       +0.j        ]
 [0.       +0.j         0.       +0.j         0.7433133+0.j
  0.       +0.j         0.       +0.j         0.       +0.j
  0.       +0.j         0.       +0.66894344j 0.       +0.j
  0.       +0.j         0.       +0.j         0.   

In [33]:
oper1=(theta*c0*tensor(I,sig_x,I,sig_x)).expm()

In [34]:
oper1==Usim1

True

In [35]:
qc1=QubitCircuit(4)

qc1.add_gate('RX',targets=1,arg_value=np.pi/2)
qc1.add_gate('RX',targets=3,arg_value=np.pi/2)
staircase_circ2(1,3,p2,qc1)
qc1.add_gate('RX',targets=1,arg_value=-1*np.pi/2)
qc1.add_gate('RX',targets=3,arg_value=-1*np.pi/2)


In [36]:
U1=qc1.propagators()
dim=np.shape(U1[0])[0]
Usim1=U1[0]
i=1
while i<(len(U1)):
    Usim1=Usim1*U1[i]
    i=i+1
    
Usim1

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[ 0.99861632  0.05258743  0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [-0.05258743  0.99861632  0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.99861632  0.05258743  0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.         -0.05258743  0.99861632  0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.99861632  0.05258743
   0.          0.          0.          0.          0.          0.
   0.          0.

In [37]:
(theta*c1*(tensor(I,sig_y,I,sig_y))).expm()

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[0.92891732+0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        -0.37028721j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.92891732+0.j         0.        +0.j
  0.        +0.j         0.        +0.37028721j 0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j        ]
 [0.        +0.j         0.        +0.j         0.92891732+0.j
  0.        +0.j         0.        +0.j         0.        +0.j
  0.        +0.j         0.        -0.37028721j 0.        +0.j
  0.      

## Checking the Commutation Relations

In [38]:
com1=oper1937*oper28-oper28*oper1937
np.any(np.array(com1))

False

In [39]:
com2=oper1937*oper46-oper46*oper1937
np.any(np.array(com2))

False

In [40]:
com3=oper1937*oper5-oper5*oper1937
np.any(np.array(com3))

True

oper1937 and oper5 donot commute

In [41]:
com4=oper28*oper46-oper46*oper28

np.any(np.array(com4))

True

oper46 and oper28 donot commute

In [42]:
com5=oper28*oper5-oper5*oper28

np.any(np.array(com5))

False

In [43]:
com6=oper46*oper5-oper5*oper46

np.any(np.array(com6))

False

## Decomposition without regarding Commutation

In [44]:
U = (theta*oper1937).expm()+(theta*oper28).expm()+(theta*oper46).expm()+ (theta*oper5).expm()
np.array(U*inp_state) 
# Can witness the presence of 11 state

array([[0.        +0.j        ],
       [0.        +0.70710678j],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [3.70710678+0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ]])

## Decomposition regarding Commutation

In [45]:
U = (theta*(oper1937+oper5)).expm()*(theta*(oper28+oper46)).expm()

inp_state=tensor(ket_0,ket_1,ket_0,ket_1)
np.array(U*inp_state) 

array([[0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.70710678j],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.70710678j],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ]])

In [46]:
op_A=oper1937+oper5
op_B=oper28+oper46
com=op_A*op_B-op_A*op_B
np.any(np.array(com))

False

`Conclusion`

Trotterization of the circuit is required.

In [47]:
# 00 input

inp_state=tensor(ket_0,ket_0,ket_0,ket_0)
a=U*inp_state
b=np.linalg.norm(np.array(U*inp_state))
out=a/b
np.array(out)

array([[1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [48]:
## 02 input

inp_state=tensor(ket_0,ket_0,ket_1,ket_1)
a=U*inp_state
b=np.linalg.norm(np.array(U*inp_state))
out=a/b
np.array(a)

array([[ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0.5+0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.70710678j],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [-0.5+0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ]])

In [49]:
## 03 input

inp_state=tensor(ket_0,ket_0,ket_1,ket_0)
a=U*inp_state
b=np.linalg.norm(np.array(U*inp_state))
out=a/b
np.array(a)

array([[ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.35355339+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.61237244j],
       [ 0.        -0.35355339j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [-0.61237244+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ]])

oper1=(1/8)*(tensor(I,sig_x,I,sig_x)+tensor(I,sig_y,I,sig_y)+tensor(sig_z,sig_x,sig_z,sig_x)+tensor(sig_z,sig_y,sig_z,sig_y)
       +tensor(I,sig_x,sig_z,sig_x)+tensor(I,sig_y,sig_z,sig_y)+tensor(sig_z,sig_x,I,sig_x)+tensor(sig_z,sig_y,I,sig_y))

a=tensor(sig_z,sig_x,sig_z,sig_x)
b=tensor(sig_z,sig_y,sig_z,sig_y)
np.any(np.array(a*b-b*a))

In [50]:
np.array(tensor(ket_1,ket_0,ket_1,ket_0))

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [51]:
op1=tensor(sig_x,sig_x)
op2=tensor(sig_y,sig_y)
op1*op2-op2*op1

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]