In [1]:
import qutip as qt
import numpy as np
from qutip import tensor
from scipy.linalg import expm
from qutip.qip.circuit import QubitCircuit, Gate

In [2]:
bdag_th=adag_th=qt.create(4)
a_th=b_th=qt.destroy(4) 

theta=complex(0,np.pi/4) #50-50 Beam splitter

#spin raising and lowering operator
sig_p=qt.destroy(2)
sig_m=qt.create(2)

#Pauli operators
I=qt.identity(2)
sig_z=qt.sigmaz()
sig_x=qt.sigmax()
sig_y=qt.sigmay()

#Qubit states
ket_0=qt.fock(2,0)
ket_1=qt.fock(2,1)

#projection operator
P0=(I+sig_z)/2
P1=(I-sig_z)/2

# Checking the error of 1BS circuit

In [3]:
oper1=tensor(sig_m,sig_p)+tensor(sig_p,sig_m)
U1=(theta*oper1).expm()

In [4]:
oper2=0.5*(tensor(sig_x,sig_x)+tensor(sig_y,sig_y))
U2=(theta*oper2).expm()

In [5]:
oper3a=tensor(sig_x,sig_x)
oper3b=tensor(sig_y,sig_y)

U3=((0.5*theta*oper3a).expm())*((0.5*theta*oper3b).expm())

In [6]:
inp = tensor(ket_0,ket_1)

In [7]:
f1=U1*inp
f2=U2*inp
f3=U3*inp

In [8]:
f2

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.70710678j]
 [0.        +0.j        ]]

In [25]:
f3

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.70710678j]
 [0.        +0.j        ]]

In [13]:
f1

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.70710678j]
 [0.        +0.j        ]]

In [10]:
A=(0.5*theta*oper3a).expm()
B=(0.5*theta*oper3b).expm()

C=A*B-B*A

C

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

# Theoretical

In [3]:
oper=tensor(bdag_th,a_th)+tensor(b_th,adag_th)

In [4]:
U=(theta*oper).expm()

In [5]:
ket_0=qt.fock(4,0)
ket_1=qt.fock(4,1)
ket_2=qt.fock(4,2)
ket_3=qt.fock(4,3)

#### 10

In [6]:
inp_state= tensor(ket_1,ket_0)

In [7]:
np.array(U*inp_state)

array([[0.        +0.j        ],
       [0.        +0.70710678j],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.70710678+0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ],
       [0.        +0.j        ]])

In [8]:
tensor(ket_1,ket_0)

Quantum object: dims = [[4, 4], [1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [9]:
tensor(ket_0,ket_1)

Quantum object: dims = [[4, 4], [1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

### 11

In [10]:
inp_state=tensor(ket_1,ket_1)

In [11]:
np.array(U*inp_state)

array([[0.+0.j        ],
       [0.+0.j        ],
       [0.+0.70710678j],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.70710678j],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ]])

In [12]:
np.array(tensor(ket_2,ket_0)+tensor(ket_0,ket_2))

array([[0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

### 20

In [13]:
inp_state=tensor(ket_2,ket_0)

In [14]:
np.array(U*inp_state)

array([[ 0. +0.j        ],
       [ 0. +0.j        ],
       [-0.5+0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.70710678j],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0.5+0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ]])

In [15]:
np.array(tensor(ket_2,ket_0)+tensor(ket_0,ket_2)+tensor(ket_1,ket_1))

array([[0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

## 21

In [16]:
inp_state=tensor(ket_2,ket_1)

In [17]:
np.array(U*inp_state)

array([[ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [-0.61237244+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.35355339j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [-0.35355339+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.61237244j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ]])

In [23]:
np.array(tensor(ket_3,ket_0))

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [152]:
np.array(tensor(ket_2,ket_1)+tensor(ket_1,ket_2)+tensor(ket_3,ket_0)+tensor(ket_0,ket_3))

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

## 30

In [154]:
inp_state=tensor(ket_3,ket_0)

In [155]:
np.array(U*inp_state)

array([[ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        -0.35355339j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [-0.61237244+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.61237244j],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.35355339+0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ],
       [ 0.        +0.j        ]])

In [164]:
np.array(tensor(ket_1,ket_2))

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [162]:
np.array(tensor(ket_0,ket_3))

array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [55]:
op1=tensor(P0,sig_m,P0,sig_p)+tensor(P0,sig_p,P0,sig_m)
op2=np.sqrt(2)*(tensor(P0,sig_m,sig_p,P1)+tensor(P0,sig_p,sig_m,P1))
op3=np.sqrt(3)*(tensor(P0,sig_m,P1,sig_m)+tensor(P0,sig_p,P1,sig_p))
op4=np.sqrt(2)*(tensor(sig_m,P1,P0,sig_p)+tensor(sig_p,P1,P0,sig_m))
op5=2*(tensor(sig_m,P1,sig_p,P1)+tensor(sig_p,P1,sig_m,P1))
op6=np.sqrt(6)*(tensor(sig_m,P1,P1,sig_m)+tensor(sig_p,P1,P1,sig_p))
op7=np.sqrt(3)*(tensor(P1,sig_p,P0,sig_p)+tensor(P1,sig_m,P0,sig_m))
op8=np.sqrt(6)*(tensor(P1,sig_p,sig_p,P1)+tensor(P1,sig_m,sig_m,P1))
op9=3*(tensor(P1,sig_p,P1,sig_m)+tensor(P1,sig_m,P1,sig_p))

In [56]:
op=op1+op2+op3+op4+op5+op6+op7+op8+op9
U1=(theta*op).expm()

In [78]:
bdag=adag=tensor(P0,sig_m)+np.sqrt(2)*tensor(sig_m,P1)+np.sqrt(3)*tensor(P1,sig_p)
b=a=tensor(P0,sig_p)+np.sqrt(2)*tensor(sig_p,P1)+np.sqrt(3)*tensor(P1,sig_m) 

In [79]:
op2=tensor(bdag,a)+tensor(adag,b)
U2=(theta*(op2)).expm()

In [80]:
U2

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          1.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          1.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j  

Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]]

In [62]:
U==U1

False

In [65]:
U

Quantum object: dims = [[4, 4], [4, 4]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.70710678+0.j          0.        +0.j
   0.        +0.j          0.        +0.70710678j  0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.5       +0.j
   0.        +0.j          0.        +0.j          0.        +0.70710678j
   0.        +0.j          0.        +0.j      

In [51]:
U1

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.70710678+0.j          0.        +0.j
   0.        +0.j          0.        +0.70710678j  0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.35355339+0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.612

In [44]:
inp_state=tensor(ket_1,ket_1,ket_0,ket_0)

In [46]:
np.array(U1*inp_state)

array([[ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [-0.5+0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.70710678j],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0.5+0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ],
       [ 0. +0.j        ]])

In [43]:
tensor(ket_0,ket_0,ket_0,ket_1)

Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [81]:
P0=(1/2)*(I+sig_z)
P1=(1/2)*(I-sig_z)

In [82]:
bdag=adag=tensor(P0,sig_m)+np.sqrt(2)*tensor(sig_m,P1)+np.sqrt(3)*tensor(P1,sig_p)
b=a=tensor(P0,sig_p)+np.sqrt(2)*tensor(sig_p,P1)+np.sqrt(3)*tensor(P1,sig_m) 

In [83]:
oper4=tensor(bdag,a)+tensor(b,adag)
U4=(theta*oper4).expm()
U4

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[ 1.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.70710678+0.j          0.        +0.j
   0.        +0.j          0.        +0.70710678j  0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j        ]
 [ 0.        +0.j          0.        +0.j          0.35355339+0.j
   0.        +0.j          0.        +0.j          0.        +0.j
   0.        +0.j          0.        +0.612

In [88]:
b_dag*b

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         0.         1.41421356]
 [0.         0.         0.         0.        ]
 [0.         0.         1.73205081 0.        ]]

In [89]:
ket_0=qt.fock(16,0)
ket_1=qt.fock(16,1)

In [90]:
U*ket_1

TypeError: Incompatible Qobj shapes

In [95]:
bdag=adag=tensor(sig_p,sig_m,I)+np.sqrt(2)*tensor(I,sig_p,sig_m)
b=a=tensor(sig_m,sig_p,I)+np.sqrt(2)*tensor(I,sig_m,sig_p)

In [97]:
b

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         1.41421356 0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         1.41421356
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]

In [101]:
ket_1=qt.fock(4,1)

In [102]:
ket_1

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]]

In [103]:
tensor(ket_0,ket_1)

Quantum object: dims = [[4, 4], [1, 1]], shape = (16, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]