In [1]:
import qutip as qt
import numpy as np
from qutip import tensor
from scipy.linalg import expm
from qutip.qip.circuit import QubitCircuit, Gate

theta=complex(0,np.pi/4)

In [2]:
sig_p=qt.destroy(2)
sig_m=qt.create(2)
I=qt.identity(2)
sig_z=qt.sigmaz()
sig_x=qt.sigmax()
sig_y=qt.sigmay()
ket_0=qt.fock(2,0)
ket_1=qt.fock(2,1)

In [3]:
oper=tensor(sig_x,I,I,sig_x)+tensor(I,sig_x,sig_x,I)

In [4]:
U=(theta*oper).expm()

In [5]:
inp_state=tensor(ket_0,ket_1,ket_0,ket_1)

In [6]:
out_state=U*inp_state

In [7]:
out_state

Quantum object: dims = [[2, 2, 2, 2], [1, 1, 1, 1]], shape = (16, 1), type = ket
Qobj data =
[[ 0. +0.j ]
 [ 0. +0.j ]
 [ 0. +0.j ]
 [ 0. +0.5j]
 [ 0. +0.j ]
 [ 0.5+0.j ]
 [ 0. +0.j ]
 [ 0. +0.j ]
 [ 0. +0.j ]
 [ 0. +0.j ]
 [-0.5+0.j ]
 [ 0. +0.j ]
 [ 0. +0.5j]
 [ 0. +0.j ]
 [ 0. +0.j ]
 [ 0. +0.j ]]

In [8]:
expect_state=(1/np.sqrt(2))*(tensor(ket_1,ket_1,ket_0,ket_0)+tensor(ket_0,ket_0,ket_1,ket_1))

In [9]:
expect_state==out_state

False

In [10]:
bdag=adag=tensor(sig_p,sig_m)+np.sqrt(2)*tensor(sig_m,sig_p)
b=a=tensor(sig_m,sig_p)+np.sqrt(2)*tensor(sig_p,sig_m) 

In [11]:
oper2=tensor(bdag,a)+tensor(b,adag)
U2=(theta*oper2).expm()

In [12]:
out_state_2=U2*inp_state

In [13]:
np.array(out_state_2)

array([[ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [-0.60569987+0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.7956932j],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ]])

In [14]:
np.array(expect_state)

array([[0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j]])

In [15]:
bdag=adag=tensor(sig_m,I)+np.sqrt(2)*tensor(I,sig_m)
b=a=tensor(sig_p,I)+np.sqrt(2)*tensor(I,sig_p)

In [16]:
oper3=tensor(bdag,a)+tensor(b,adag)
U3=(theta*oper3).expm()

In [17]:
inp_state=tensor(ket_1,ket_0,ket_1,ket_0)

In [18]:
out_state=U3*inp_state

In [19]:
np.array(out_state)

array([[ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        -0.0331117j],
       [ 0.        +0.j       ],
       [-0.46948928+0.j       ],
       [-0.49796859+0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [-0.49796859+0.j       ],
       [ 0.53051072+0.j       ],
       [ 0.        +0.j       ],
       [ 0.        -0.0331117j],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ],
       [ 0.        +0.j       ]])

In [20]:
expect_state=(1/np.sqrt(2))*(tensor(ket_1,ket_1,ket_0,ket_0)+tensor(ket_0,ket_0,ket_1,ket_1))

In [21]:
ket00=tensor(ket_0,ket_0)
ket01=tensor(ket_0,ket_1)
ket10=tensor(ket_1,ket_0)
ket11=tensor(ket_1,ket_1)

In [22]:
u1=ket00*ket01.dag()

In [23]:
u2=ket01*ket11.dag()

### Projector Method

#### Grey encoding

0 ==> 00      or   00 $\newline$
1 ==> 01      or   10 $\newline$
2 ==> 11      or   11 $\newline$
3 ==> 10      or   01 $\newline$

#### Projector Operator

P0 = $\frac{I+\sigma_{z}}{2}=$\begin{bmatrix} 1 & 0 \\ 0 & 0 \end{bmatrix} 

P1 = $\frac{I-\sigma_{z}}{2}=$\begin{bmatrix} 0 & 0 \\ 0 & 1 \end{bmatrix} 


P0 |0> = |0> and P0|1> = 0

P1 |0> = 0 and P0|1> = |1>

#### Creation and Annihilation operator for Gray encoding

$b^{\dagger}= P_{0} \sigma_{-} + \sqrt{2} \sigma_{-} P_{1} + \sqrt{3} P_{1} \sigma_{+} \newline$
$b= P_{0} \sigma_{+} + \sqrt{2} \sigma_{+} P_{1} + \sqrt{3} P_{1} \sigma_{-}$

In [24]:
P0=(1/2)*(I+sig_z)
P1=(1/2)*(I-sig_z)

In [25]:
bdag=adag=tensor(P0,sig_m)+np.sqrt(2)*tensor(sig_m,P1)+np.sqrt(3)*tensor(P1,sig_p)
b=a=tensor(P0,sig_p)+np.sqrt(2)*tensor(sig_p,P1)+np.sqrt(3)*tensor(P1,sig_m) 

In [26]:
oper4=tensor(bdag,a)+tensor(b,adag)
U4=(theta*oper4).expm()

In [28]:
inp_state=tensor(ket_0,ket_1,ket_0,ket_1)

In [29]:
out_state=U4*inp_state
np.array(out_state)

array([[0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.70710678j],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.70710678j],
       [0.+0.j        ],
       [0.+0.j        ],
       [0.+0.j        ]])

In [11]:
expect_state=(1/np.sqrt(2))*(tensor(ket_1,ket_1,ket_0,ket_0)+tensor(ket_0,ket_0,ket_1,ket_1))
np.array(expect_state)

array([[0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j],
       [0.        +0.j],
       [0.        +0.j]])

In [12]:
tensor(P0,sig_p)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [13]:
tensor(sig_p,P0)

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [14]:
op1=tensor(bdag,a)
op2=tensor(b,adag)
com=op1*op2-op2*op1

In [15]:
np.any(np.array(com))

True

In [16]:
com

Quantum object: dims = [[2, 2, 2, 2], [2, 2, 2, 2]], shape = (16, 16), type = oper, isherm = True
Qobj data =
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -3.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -6.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  9.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  2.  0.  0.  0.]
 [ 0.  0.  0.  0.  